### PR TITLE
add unit tests for erlcloud_ddb_streams

### PR DESCRIPTION
**Pull request by nalundgaard**
- based on (rather broken) AWS example documentation. I cross-checked with format in real API calls where the examples seemed wonky, and I'll be reporting the inconsistencies to Amazon soon.

### CODE REVIEW

**Comment by smilerlee** [comment]
Yeah, I also noticed that. Glad to see the tests are ready

**Comment by nalundgaard** [comment]
@smilerlee I found a few issues in the documentation (and also the alignment of the eunit tests), so I've fixed those. I think this is now ready to merge.

**Comment by smilerlee** [comment]
Thanks, @nalundgaard. I'll merge this PR a little later.

**Comment by smilerlee** [comment]
Hi @nalundgaard . I've just run the test cases and I got 3 failures out of 12. The error reason output is:

```
in function jsx_decoder:key/4 (src/jsx_decoder.erl, line 303)
in call from erlcloud_ddb_streams_impl:request_and_retry/4 (src/erlcloud_ddb_streams_impl.erl, line 177)
in call from erlcloud_ddb_streams:describe_stream/3 (src/erlcloud_ddb_streams.erl, line 523)
**error:badarg


in function jsx_decoder:key/4 (src/jsx_decoder.erl, line 303)
in call from erlcloud_ddb_streams_impl:request_and_retry/4 (src/erlcloud_ddb_streams_impl.erl, line 177)
in call from erlcloud_ddb_streams:describe_stream/3 (src/erlcloud_ddb_streams.erl, line 523)
**error:badarg


in function jsx_decoder:key/4 (src/jsx_decoder.erl, line 303)
in call from erlcloud_ddb_streams_impl:request_and_retry/4 (src/erlcloud_ddb_streams_impl.erl, line 177)
in call from erlcloud_ddb_streams:describe_stream/3 (src/erlcloud_ddb_streams.erl, line 523)
in call from erlcloud_ddb_streams_tests:'-output_test/2-fun-1-'/3 (test/erlcloud_ddb_streams_tests.erl, line 115)
**error:badarg

ERROR: One or more eunit tests failed.
ERROR: eunit failed while processing /Users/smiler/works/github/erlcloud: rebar_abort
```

Would you please have a detailed look? Thanks.

**Comment by nalundgaard** [comment]
How are you running the tests, and what Erlang are you using? I get this on R16B03-1 and 17.4:

``` sh
$ rebar eunit suites=erlcloud_ddb_streams_tests
==> erlcloud (eunit)
  All 12 tests passed.
```

**Comment by smilerlee** [comment]
It turned out that I got a old version of `jsx` in my `deps` folder. Just updated it to the latest version and everything seems right now. Appreciate your feedback.

**Pull request merged**
