### PR TITLE
Add documentation for Streams API functions

### PR DESCRIPTION
**Pull request by nalundgaard**
- based on AWS API documentation examples.

### CODE REVIEW

**Comment by nalundgaard** [comment]
cf. gleber/erlcloud#189 again.

**Comment by nalundgaard** [comment]
@smilerlee I just re-pushed the commit with the fixes for the two issues you caught. Thanks again.

**Comment by smilerlee** [comment]
Thanks. I was supposed to squash all these commits on this preview branch together, since all changes was made by myself. But I changed my mind now, considered you made commits on this branch too. Thanks for the documentation again

**Comment by nalundgaard** [comment]
@smilerlee I just re-pushed the commit with a fix for the errantly typed attributes in the get_records example. Hope it's ready now.

**Comment by smilerlee** [comment]
It seems perfect! Thank you, @nalundgaard

**Pull request merged**
